// Copyright 2024-2026 Zunor
// SPDX-License-Identifier: Apache-2.0

use super::*;

pub(crate) fn logical_name<Child>(op: &LogicalOperator<Child>) -> &'static str {
    match op {
        LogicalOperator::Get(_) => "GET",
        LogicalOperator::SubplanRef(_) => "BOUND_REFERENCE",
        LogicalOperator::Filter(_) => "FILTER",
        LogicalOperator::Projection(_) => "PROJECTION",
        LogicalOperator::RowFetch(_) => "ROW_FETCH",
        LogicalOperator::ExternalProject(_) => "EXTERNAL_PROJECT",
        LogicalOperator::ExternalTable(_) => "EXTERNAL_TABLE",
        LogicalOperator::Limit(_) => "LIMIT",
        LogicalOperator::Order(_) => "ORDER",
        LogicalOperator::TopN(_) => "TOP_N",
        LogicalOperator::CreateTable(_) => "CREATE_TABLE",
        LogicalOperator::CreateRoutine(_) => "CREATE_ROUTINE",
        LogicalOperator::Alter(_) => "ALTER",
        LogicalOperator::CreateSequence(_) => "CREATE_SEQUENCE",
        LogicalOperator::CreateSchema(_) => "CREATE_SCHEMA",
        LogicalOperator::CreateIndex(_) => "CREATE_INDEX",
        LogicalOperator::CreateView(_) => "CREATE_VIEW",
        LogicalOperator::Drop(_) => "DROP",
        LogicalOperator::CreatePropertyGraph(_) => "CREATE_PROPERTY_GRAPH",
        LogicalOperator::DropPropertyGraph(_) => "DROP_PROPERTY_GRAPH",
        LogicalOperator::RefreshPropertyGraph(_) => "REFRESH_PROPERTY_GRAPH",
        LogicalOperator::Aggregate(_) => "AGGREGATE",
        LogicalOperator::Insert(_) => "INSERT",
        LogicalOperator::Delete(_) => "DELETE",
        LogicalOperator::Update(_) => "UPDATE",
        LogicalOperator::ExpressionGet(_) => "EXPRESSION_GET",
        LogicalOperator::Join(_) => "JOIN",
        LogicalOperator::DelimGet(_) => "DELIM_GET",
        LogicalOperator::DependentJoin(_) => "DEPENDENT_JOIN",
        LogicalOperator::SetOperation(_) => "SET_OPERATION",
        LogicalOperator::Distinct(_) => "DISTINCT",
        LogicalOperator::Window(_) => "WINDOW",
        LogicalOperator::Explain(_) => "EXPLAIN",
        LogicalOperator::EmptyResult(_) => "EMPTY_RESULT",
        LogicalOperator::MaterializedCTE(_) => "MATERIALIZED_CTE",
        LogicalOperator::RecursiveCTE(_) => "RECURSIVE_CTE",
        LogicalOperator::CTERef(_) => "CTE_REF",
        LogicalOperator::TableFunctionGet(_) => "TABLE_FUNCTION_GET",
        LogicalOperator::SearchScan(_) => "SEARCH_SCAN",
        LogicalOperator::FullTextFilterScan(_) => "FULL_TEXT_FILTER_SCAN",
        LogicalOperator::CopyTo(_) => "COPY_TO",
        LogicalOperator::GraphMatch(_) => "GRAPH_MATCH",
        LogicalOperator::GraphScan(_) => "GRAPH_SCAN",
        LogicalOperator::GraphExpand(_) => "GRAPH_EXPAND",
        LogicalOperator::DummyScan => "DUMMY_SCAN",
    }
}
