[package]
name = "paro-journal"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
paro-common = { workspace = true }
bincode = { workspace = true }
crc32c = "0.6"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
parking_lot = { workspace = true }
paro-common = { workspace = true, features = ["test-support"] }
tempfile = "3.8"

[[bench]]
name = "journal_pipeline"
harness = false
