// Copyright 2024-2026 Zunor
// SPDX-License-Identifier: Apache-2.0

//! Generated by `tools/ci/generate_optimizer_calibration.py`.
//! Do not edit by hand; update the benchmark calibration artifact.

use super::{BuiltinCoefficient, OpClassId, ResourceDimension};

pub(super) const REVISION: u32 = 1;
pub(super) const HARDWARE_CLASS: &str = "portable-cpu-v1";
pub(super) const CORPUS_ID: &str = "optimizer-cost-bootstrap-2026-08";
pub(super) const PROVENANCE: &str = "bootstrap";
pub(super) const RISK_WEIGHT: f64 = 0.500000;

pub(super) const COEFFICIENTS: &[BuiltinCoefficient] = &[
    // hash_build_row: integer_hash_join
    BuiltinCoefficient {
        class: OpClassId(1),
        dimension: ResourceDimension::Cpu,
        expected: 1.300000,
        risk: 2.600000,
        latency_expected: 1.300000,
        latency_upper: 3.900000,
    },
    // hash_probe_row: integer_hash_join
    BuiltinCoefficient {
        class: OpClassId(2),
        dimension: ResourceDimension::Cpu,
        expected: 0.700000,
        risk: 1.500000,
        latency_expected: 0.700000,
        latency_upper: 2.200000,
    },
    // nested_loop_pair: integer_hash_join
    BuiltinCoefficient {
        class: OpClassId(3),
        dimension: ResourceDimension::Cpu,
        expected: 1.000000,
        risk: 3.000000,
        latency_expected: 1.000000,
        latency_upper: 4.000000,
    },
    // sort_compare: large_sort
    BuiltinCoefficient {
        class: OpClassId(4),
        dimension: ResourceDimension::Cpu,
        expected: 1.200000,
        risk: 3.600000,
        latency_expected: 1.200000,
        latency_upper: 5.000000,
    },
    // range_join_row: sort_range_join_full
    BuiltinCoefficient {
        class: OpClassId(5),
        dimension: ResourceDimension::Cpu,
        expected: 0.650000,
        risk: 1.800000,
        latency_expected: 0.650000,
        latency_upper: 2.400000,
    },
    // ie_join_row: classic_ie_join_selective
    BuiltinCoefficient {
        class: OpClassId(6),
        dimension: ResourceDimension::Cpu,
        expected: 0.800000,
        risk: 2.100000,
        latency_expected: 0.800000,
        latency_upper: 2.800000,
    },
    // hash_aggregate_row: high_cardinality_aggregate
    BuiltinCoefficient {
        class: OpClassId(7),
        dimension: ResourceDimension::Cpu,
        expected: 0.900000,
        risk: 2.200000,
        latency_expected: 0.900000,
        latency_upper: 3.000000,
    },
    // hash_aggregate_group: high_cardinality_aggregate
    BuiltinCoefficient {
        class: OpClassId(8),
        dimension: ResourceDimension::Cpu,
        expected: 1.500000,
        risk: 3.500000,
        latency_expected: 1.500000,
        latency_upper: 4.500000,
    },
    // perfect_aggregate_row: high_cardinality_aggregate
    BuiltinCoefficient {
        class: OpClassId(9),
        dimension: ResourceDimension::Cpu,
        expected: 0.450000,
        risk: 1.100000,
        latency_expected: 0.450000,
        latency_upper: 1.600000,
    },
    // perfect_aggregate_slot: high_cardinality_aggregate
    BuiltinCoefficient {
        class: OpClassId(10),
        dimension: ResourceDimension::Cpu,
        expected: 0.200000,
        risk: 0.550000,
        latency_expected: 0.200000,
        latency_upper: 0.800000,
    },
    // runtime_filter_build_row: expr_runtime_filter
    BuiltinCoefficient {
        class: OpClassId(11),
        dimension: ResourceDimension::Cpu,
        expected: 0.150000,
        risk: 0.600000,
        latency_expected: 0.150000,
        latency_upper: 0.800000,
    },
    // runtime_filter_apply_row: expr_runtime_filter
    BuiltinCoefficient {
        class: OpClassId(12),
        dimension: ResourceDimension::Cpu,
        expected: 0.100000,
        risk: 0.400000,
        latency_expected: 0.100000,
        latency_upper: 0.600000,
    },
    // window_row: ordered_aggregate
    BuiltinCoefficient {
        class: OpClassId(13),
        dimension: ResourceDimension::Cpu,
        expected: 1.400000,
        risk: 3.800000,
        latency_expected: 1.400000,
        latency_upper: 5.200000,
    },
    // partition_aggregate_window_row: ordered_aggregate
    BuiltinCoefficient {
        class: OpClassId(14),
        dimension: ResourceDimension::Cpu,
        expected: 0.550000,
        risk: 1.400000,
        latency_expected: 0.550000,
        latency_upper: 2.000000,
    },
    // singleton_aggregate_project_row: grouping_sets_aggregate
    BuiltinCoefficient {
        class: OpClassId(15),
        dimension: ResourceDimension::Cpu,
        expected: 0.250000,
        risk: 0.700000,
        latency_expected: 0.250000,
        latency_upper: 1.000000,
    },
    // tuple_byte_block: string_hash_join
    BuiltinCoefficient {
        class: OpClassId(16),
        dimension: ResourceDimension::MemoryRead,
        expected: 0.250000,
        risk: 1.000000,
        latency_expected: 0.100000,
        latency_upper: 0.500000,
    },
    // enforcer_stream_row: count_filter
    BuiltinCoefficient {
        class: OpClassId(20001),
        dimension: ResourceDimension::Cpu,
        expected: 0.250000,
        risk: 1.000000,
        latency_expected: 0.250000,
        latency_upper: 1.000000,
    },
    // enforcer_sort_compare: large_sort
    BuiltinCoefficient {
        class: OpClassId(20002),
        dimension: ResourceDimension::Cpu,
        expected: 1.000000,
        risk: 4.000000,
        latency_expected: 1.000000,
        latency_upper: 6.000000,
    },
    // enforcer_random_fetch: selective_rowset_scan
    BuiltinCoefficient {
        class: OpClassId(20003),
        dimension: ResourceDimension::RandomIo,
        expected: 1.000000,
        risk: 6.000000,
        latency_expected: 2.000000,
        latency_upper: 12.000000,
    },
    // enforcer_spill_page: forced_external_hash_join
    BuiltinCoefficient {
        class: OpClassId(20004),
        dimension: ResourceDimension::SequentialIo,
        expected: 2.000000,
        risk: 8.000000,
        latency_expected: 2.000000,
        latency_upper: 10.000000,
    },
];
