[package]
name = "paro-server"
version = { workspace = true }
edition = { workspace = true }

[lints.clippy]
manual-slice-fill = "allow"

[dependencies]
paro-common = { workspace = true }
paro-catalog = { workspace = true }
paro-session = { workspace = true }
paro-instance = { workspace = true }
paro-execution = { workspace = true }
paro-parser = { workspace = true }
paro-function = { workspace = true }
paro-storage = { workspace = true }
pgwire = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itoa = { workspace = true }
ryu = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
bytesize = { workspace = true }
rand = "0.8"

[dev-dependencies]
paro-common = { workspace = true, features = ["test-support"] }
tempfile = "3.8"
